development:
  adapter: postgresql
  encoding: unicode
  database: lpl_onboarding_backend_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: lpl_onboarding_backend_test
  pool: 5
  host: localhost
